//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ULSDBEntities : DbContext
    {
        public ULSDBEntities()
            : base("name=ULSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<PAPTbl_PermissionPages> PAPTbl_PermissionPages { get; set; }
        public DbSet<PAPTbl_PermissionUsers> PAPTbl_PermissionUsers { get; set; }
        public DbSet<ULSTbl_Books> ULSTbl_Books { get; set; }
        public DbSet<ULSTbl_Categories> ULSTbl_Categories { get; set; }
        public DbSet<ULSTbl_Faq> ULSTbl_Faq { get; set; }
        public DbSet<ULSTbl_SiteSetting> ULSTbl_SiteSetting { get; set; }
        public DbSet<ULSTbl_Users> ULSTbl_Users { get; set; }
        public DbSet<ULSTbl_Reserve> ULSTbl_Reserve { get; set; }
        public DbSet<PAPMyDevice> PAPMyDevice { get; set; }
    }
}
