//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPTbl_PermissionPages
    {
        public long ID { get; set; }
        public string PageNameForDisplay { get; set; }
        public string PageName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> IsPermission { get; set; }
    }
}
