//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULSTbl_Reserve
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public Nullable<long> BookID { get; set; }
        public string CustomCode { get; set; }
        public Nullable<System.DateTime> ReserveStartDate { get; set; }
        public Nullable<System.DateTime> ReserveEndDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Renewal { get; set; }
    }
}
