//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULSTbl_Users
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PicName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<long> Liability { get; set; }
        public string UserNameAdder { get; set; }
        public Nullable<System.DateTime> chpass { get; set; }
    }
}
