//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULSTbl_Books
    {
        public int ID { get; set; }
        public string BookTitle { get; set; }
        public string PicName { get; set; }
        public string TranslatorName { get; set; }
        public string PublisherName { get; set; }
        public string AuthorName { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserNameAdder { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
