//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULSTbl_SiteSetting
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string MapLink { get; set; }
        public string ShortAboutUs { get; set; }
        public string AboutUs { get; set; }
        public Nullable<int> ReserveDay { get; set; }
        public Nullable<int> MaxUserReserve { get; set; }
        public Nullable<int> ReserveAgain { get; set; }
        public Nullable<long> Liability { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> CanRes { get; set; }
    }
}
