//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULSTbl_Faq
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserNameAdder { get; set; }
    }
}
